### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by uraway**
Add .editorconfig file to define coding styles.

http://editorconfig.org/

### CODE REVIEW

**Comment by vasanthk** [comment]
@uraway Never used this. Curious if this would cause trouble for people who use tabs for indentations by default? Just trying to keep the boilerplate as less opinionated as possible.

**Comment by uraway** [comment]
Ohh I could not imagine that. Thanks.

**Comment by zedd45** [comment]
Usually, `.editorconfig` is a good idea to enforce uniform code standards in the repo, so this might be worth more discussion.

**Comment by vasanthk** [comment]
@zedd45 I am open to discussion and wanted to know more. This PR was closed by the OP.

**Comment by zedd45** [comment]
The idea is that [`.editorconfig`](http://editorconfig.org/) tells editors like `Sublime`, `Atom` and IDEs like `Intellij IDEA` how to format code so you don't get `git diffs` on things like spaces vs tabs.  It's worth looking into, but it's not a requirement.  I like to use it on my projects.  

It basically enforces consistency like a linter would, but it does so _via the editor_ so we don't have to run checks, it just does it!

**Pull request closed without merging**
